# Generated by Django 3.2.7 on 2022-01-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    )
                ),
                (
                    'title',
                    models.CharField(max_length=100, verbose_name='Title')
                ),
                ('body', models.TextField(verbose_name='Body')),
                ('trash_by_user', models.BooleanField(default=False)),
                ('trash_by_recipient', models.BooleanField(default=False)),
            ],
        ),
    ]
