# Generated by Django 3.2.7 on 2022-01-16 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messaging', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='recipient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='Recipient',
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='User',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
