# .circleci/config.yaml
version: 2.1

jobs:
    test:
        docker:
            - image: cimg/python:3.10.1
        steps:
            - checkout
            - restore_cache:
                key: deps9-{{ .Branch }}-{{ checksum "backend/requirements.txt" }}

            - run: pip install --user -r backend/requirements.txt
            - save_cache:
                key: deps9-{{ .Branch }}-{{ checksum "backend/requirements.txt" }}
                paths:
                  - /home/circleci/.cache/pip
                  - /home/circleci/.pyenv

            - run: python backend/manage.py test

    flake8:
        docker:
            - image: cimg/python:3.10.1
        steps:
            - checkout

            - restore_cache:
                  key: deps9-{{ .Branch }}-{{ checksum "backend/requirements.txt" }}
            - run: pip install --user -r backend/requirements.txt
            - save_cache:
                  key: deps9-{{ .Branch }}-{{ checksum "backend/requirements.txt" }}
                  paths:
                      - /home/circleci/.cache/pip
                      - /home/circleci/.pyenv
            - run: cd backend; flake8
workflows:
    version: 2
    build_and_test:
        jobs:
            - flake8
            - test